package goods;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * Holds a food object, which is generated by a farm or some sort of other
 * production.
 * @author inhaler
 *
 */
public class Food implements good {
	
	private int foodId;
	/*static list of all base foods. this can be used in food generation/creation
	 * when a new food is created, it must be added to this list
	*/
	public static ConcurrentMap<String,Food> baseFoods = new ConcurrentHashMap<String,Food>();
	
	
	
	public Food() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public int getMass() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int getVolume() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int assessValue() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void simulateStep() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public String getId() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void generate() {
		// TODO Auto-generated method stub
		
	}

}
