package goods;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

import topLevel.NodeMain;

/**
 * Holds a food object, which is generated by a farm or some sort of other
 * production.
 * @author inhaler
 *
 */
public class Food implements good {
	
	//the id for the food, or BASE_FOOD_ID if a base food.
	private String id;
	public static final String BASE_FOOD_ID = "Base Food"; 
	public static final int EXPIRED_FOOD_VALUE = -10;
	//the name of the food
	private String foodName;
	/*static list of all base foods. this can be used in food generation/creation
	 * when a new food is created, it must be added to this list
	*/
	public static ConcurrentMap<String,Food> baseFoods = new ConcurrentHashMap<String,Food>();
	
	/*
	 * Food stats
	 */
	private int nutritionValue;
	private int tasteValue;
	private int timeLeft;
	private int volume;
	private int mass;
	
	public static void createBaseFood(Food f) {
		baseFoods.putIfAbsent(f.foodName, f);
	}
	
	
	public Food() {
		
	}

	@Override
	public int getMass() {
		return mass;
	}

	@Override
	public int getVolume() {
		return volume;
	}

	@Override
	public int assessValue() {
		//TODO: add assess value function
		return 0;
	}

	@Override
	public void simulateStep() {
		this.timeLeft--;
		
		if (timeLeft <0) {
			this.tasteValue = EXPIRED_FOOD_VALUE;
			this.nutritionValue = EXPIRED_FOOD_VALUE;
		}
		
	}

	@Override
	public String getId() {
		return id;
	}

	@Override
	public void generate() {
		this.setId(NodeMain.genID());
		
	}

	public String getFoodName() {
		return foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public int getNutritionValue() {
		return nutritionValue;
	}

	public void setNutritionValue(int nutritionValue) {
		this.nutritionValue = nutritionValue;
	}

	public int getTasteValue() {
		return tasteValue;
	}

	public void setTasteValue(int tasteValue) {
		this.tasteValue = tasteValue;
	}

	@Override
	public void setGoodStats(int volume, int mass) {
		this.volume = volume;
		this.mass = mass;
	}

	public int getTimeLeft() {
		return timeLeft;
	}

	public void setTimeLeft(int timeLeft) {
		this.timeLeft = timeLeft;
	}
	
	public String toString() {
		return "Food: " + this.foodName +" Nurtition: " + nutritionValue + " Taste: " + tasteValue + goodStatToString();
	}

	public void setId(String id) {
		this.id = id;
	}

	@Override
	public int getGoodType() {
		return good.GOOD_TYPE_FOOD;
	}

}
